In [1]:
import numpy as np
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [3]:
np.full((3,5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [6]:
np.linspace(10, 15, 2)

array([ 10.,  15.])

In [7]:
np.random.random((3,3))


array([[ 0.54825463,  0.12229313,  0.8179318 ],
       [ 0.89553834,  0.07141805,  0.27080164],
       [ 0.26256089,  0.5023079 ,  0.06056364]])

In [8]:
np.random.normal(0, 1, (3,3))

array([[-2.3759139 ,  1.1515705 ,  0.65804089],
       [-0.8858611 , -0.26003245,  1.1820278 ],
       [-1.43222044, -0.30995624, -1.77019038]])

In [9]:
np.random.randint(0, 10, (3,3))

array([[4, 1, 0],
       [2, 9, 8],
       [0, 8, 8]])

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
np.empty(5)

array([ 0.,  1.,  2.,  3.,  4.])

In [15]:
x2 = np.random.randint(0, 10, (3,3))

In [18]:
x2

array([[1, 8, 6],
       [5, 5, 6],
       [6, 3, 5]])

In [19]:
x2[:, 0]

array([1, 5, 6])

In [20]:
x2[0, :]

array([1, 8, 6])

In [21]:
x2[0]

array([1, 8, 6])

In [22]:
grid = np.arange(1,10).reshape(3,3)

In [23]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
x = np.array([1,2,3])

In [26]:
x.reshape((1,3))

array([[1, 2, 3]])

In [27]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [28]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [29]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [32]:
grid = np.array([[1,2,3], [4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])
np.vstack([x, grid])
y = np.array([[99], [99]])


In [40]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [41]:
theta = np.linspace(0, np.pi, 3)
theta

array([ 0.        ,  1.57079633,  3.14159265])

In [42]:
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[  0.00000000e+00   1.00000000e+00   1.22464680e-16]
[  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
[  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


In [43]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = [1,2,3]
print(np.exp2(x))
print(np.power(3, x))

[ 2.  4.  8.]
[ 3  9 27]


In [48]:
x = np.arange(1, 6)
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [49]:
big_array = np.random.rand(1000)
%timeit sum(big_array)
%timeit np.sum(big_array)

102 µs ± 2.66 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.63 µs ± 61.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [53]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [54]:
x = np.linspace(0,5, 50)
x

array([ 0.        ,  0.10204082,  0.20408163,  0.30612245,  0.40816327,
        0.51020408,  0.6122449 ,  0.71428571,  0.81632653,  0.91836735,
        1.02040816,  1.12244898,  1.2244898 ,  1.32653061,  1.42857143,
        1.53061224,  1.63265306,  1.73469388,  1.83673469,  1.93877551,
        2.04081633,  2.14285714,  2.24489796,  2.34693878,  2.44897959,
        2.55102041,  2.65306122,  2.75510204,  2.85714286,  2.95918367,
        3.06122449,  3.16326531,  3.26530612,  3.36734694,  3.46938776,
        3.57142857,  3.67346939,  3.7755102 ,  3.87755102,  3.97959184,
        4.08163265,  4.18367347,  4.28571429,  4.3877551 ,  4.48979592,
        4.59183673,  4.69387755,  4.79591837,  4.89795918,  5.        ])

In [58]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [56]:
x <= 3

array([ True,  True,  True, False, False], dtype=bool)

In [60]:
np.sum(x > 6)

3

In [62]:
np.sum( x > 6, axis=1)

array([0, 2, 1])

In [63]:
np.any(x > 8)

True

In [64]:
np.all( x < 10)

True

In [66]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False, False], dtype=bool)

In [70]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [71]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [72]:
ind = [3,7,4]
x[ind]

array([71, 86, 60])

In [73]:
ind = np.array([[3,7], [4,5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [2]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))


In [3]:
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [4]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [5]:
x = np.zeros(4, dtype=int)

In [6]:
x

array([0, 0, 0, 0])

In [7]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 'formats':('U10', 'i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [8]:
name = ['Alice', 'Bob', 'Cathy', 'Doung']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [9]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25,  55. ) ('Bob', 45,  85.5) ('Cathy', 37,  68. )
 ('Doung', 19,  61.5)]
